apiVersion: v1
kind: Pod
metadata:
  name: app-frontend-pod
  labels:
    type: frontend
spec:
  containers:
  - name: frontend-app
    image: vimalsmenon/app-frontend:latest
    ports:
    - containerPort: 3000
