apiVersion: v1
kind: Pod
metadata:
  name: app-frontend-pod
  namespace: k8s-app
  labels:
    tier: frontend
spec:
  containers:
  - name: frontend-app
    image: vimalsmenon/app-frontend:latest
    ports:
    - containerPort: 3000
