apiVersion: v1
kind: Pod
metadata:
  name: app-frontend-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: frontend-app
    image: vimalsmenon/app-frontend:latest
    ports:
    - containerPort: 3000
    env:
      - name: NEXT_PUBLIC_APP_NAME
        valueFrom:
          configMapKeyRef:
            name: app-data
            key: APP_NAME
