apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-job
  namespace: k8s-app
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:glibc
            command: ["ls",  "-ltra"]
          restartPolicy: Never
