apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: k8s-app
spec:
  containers:
  - name: stress-test
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "IG", "--vm-hand", "1"]
    resources:
      requests:
        cpu: "1"
        memory: "10Gi"
      limits:
        cpu: "2"
        memory: "15Gi"
