apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: k8s-app
spec:
  containers:
    - name: stress-test
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "4G", "--vm-hang", "1.2"]
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
  restartPolicy: Never
