apiVersion: v1
kind: Pod
metadata:
  name: front-end-app
  labels:
    type: front-end
spec:
  containers:
  - name: front-end-app
    image: vimalsmenon/front-end-app:0.0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
    env:
    - name: NEXT_PUBLIC_APP_NAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: APP_DATA
