apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app-deployment
  labels:
    type: front-end-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end-app
  template: 
    metadata:
      name: front-end-app-pod
      labels:
        app: front-end-app
    spec:
      containers:
      - name: front-end-app
        image: vimalsmenon/front-end-app:0.0.0
        ports:
        - containerPort: 3000