apiVersion: v1
kind: Service
metadata:
  name: front-end-app-service
  labels:
    type: front-end-service
spec:
  type: ClusterIP
  selector:
    app: front-end-app
  ports: 
    - port: 3000
      targetPort: 3000