apiVersion: v1
kind: Service
metadata:
  name: front-end-app-service
  labels:
    type: front-end-service
spec:
  type: NodePort
  selector:
    app: front-end-app
  ports: 
    - name: app
      port: 3000
      targetPort: 3000
      nodePort: 30000